In [ ]:
#import lib
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/supplement.csv")

In [ ]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,Yes,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,Yes,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,Yes,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,Yes,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,Yes,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,S2,L3,R2,2019-05-31,1,Yes,51,37272.00
188336,T1188337,153,S4,L2,R1,2019-05-31,1,No,90,54572.64
188337,T1188338,154,S1,L3,R2,2019-05-31,1,No,56,31624.56
188338,T1188339,155,S3,L1,R2,2019-05-31,1,Yes,70,49162.41
188339,T1188340,152,S2,L1,R1,2019-05-31,1,No,47,37977.00

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             188340 non-null  object
 1   Store_id       188340 non-null  int64
 2   Store_Type     188340 non-null  object
 3   Location_Type  188340 non-null  object
 4   Region_Code    188340 non-null  object
 5   Date           188340 non-null  object
 6   Holiday        188340 non-null  int64
 7   Discount       188340 non-null  object
 8   #Order         188340 non-null  int64
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB

In [ ]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [ ]:
dataset.describe()

            Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [ ]:
#visualization
!pip install plotly
import plotly.express as px

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.9/dist-packages (5.13.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from plotly) (8.2.2)

In [ ]:
pie=dataset["Store_Type"].value_counts()
store=pie.index
orders=pie.values

fig=px.pie(dataset,values=orders,names=store)
fig.show()

In [ ]:
pie2=dataset["Location_Type"].value_counts()
location=pie2.index
orders=pie2.values

fig=px.pie(dataset,values=orders,names=location)
fig.show()

In [ ]:
pie3=dataset["Discount"].value_counts()
Discount=pie3.index
orders=pie3.values

fig=px.pie(dataset,values=orders,names=Discount)
fig.show()

In [ ]:
pie4=dataset["Holiday"].value_counts()
holiday=pie4.index
orders=pie4.values

fig=px.pie(dataset,values=orders,names=holiday)
fig.show()

In [ ]:
dataset["Discount"]=dataset["Discount"].map({"No":0,"Yes":1})

In [ ]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,S2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,S4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,S1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,S3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,S2,L1,R1,2019-05-31,1,0,47,37977.00

In [ ]:
dataset["Store_Type"]=dataset["Store_Type"].map({"S1":1,"S2":2,"S3":3,"S4":4})

In [ ]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,L1,R1,2019-05-31,1,0,47,37977.00

In [ ]:
dataset["Location_Type"]=dataset["Location_Type"].map({"L1":1,"L2":2,"L3":3,"L4":4,"L5":5})

In [ ]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,1,R1,2019-05-31,1,0,47,37977.00

In [ ]:
dataset["Region_Code"]=dataset["Region_Code"].map({"R1":1,"R2":2,"R3":3,"R4":4})

In [ ]:
dataset

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,3,1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,2,1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,2,1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,3,1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,3,4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,3,2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,2,1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,3,2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,1,2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,1,1,2019-05-31,1,0,47,37977.00

In [ ]:
x=np.array(dataset[["Store_Type","Location_Type","Region_Code","Holiday","Discount"]])
y=np.array(dataset["#Order"])

In [ ]:
x

array([[1, 3, 1, 1, 1],
       [4, 2, 1, 1, 1],
       [3, 2, 1, 1, 1],
       ...,
       [1, 3, 2, 1, 0],
       [3, 1, 2, 1, 1],
       [2, 1, 1, 1, 0]])

In [ ]:
y

array([ 9, 60, 42, ..., 56, 70, 47])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train

array([[2, 3, 3, 0, 0],
       [3, 1, 1, 0, 0],
       [4, 1, 1, 0, 0],
       ...,
       [1, 1, 4, 0, 1],
       [1, 3, 3, 0, 1],
       [2, 4, 2, 0, 0]])

In [ ]:
len(x_train)

150672

In [ ]:
pip install lightgbm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lightgbm in /usr/local/lib/python3.9/dist-packages (3.3.5)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/dist-packages (from lightgbm) (0.40.0)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.9/dist-packages (from lightgbm) (1.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from lightgbm) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from lightgbm) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn!=0.22.0->lightgbm) (3.1.0)

In [ ]:
import lightgbm as lgb
model = lgb.LGBMRegressor()

In [ ]:
model.fit(x_train,y_train)

LGBMRegressor()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([ 50.19023435, 104.21578729,  68.08376523, ...,  45.33995367,
        62.53550356,  84.79858358])

In [ ]:
y_test

array([ 54, 111,  59, ...,  40,  69,  68])

In [ ]:
accuracy=model.score(x_test,y_test)
print(accuracy)

0.6138769671511071

In [ ]:
data=pd.DataFrame (data={"Predicted Orders":y_pred.flatten()})

In [ ]:
data

       Predicted Orders
0             50.190234
1            104.215787
2             68.083765
3             84.798959
4             55.713755
...                 ...
37663         68.083765
37664         52.210501
37665         45.339954
37666         62.535504
37667         84.798584

[37668 rows x 1 columns]